#!/usr/bin/env bash
set -eo pipefail

###
# Install buildpacks
# You'll probably want to commit stuff after running the update
# 
# Original Copyright 2015 Engine Yard, Inc. Modification Copyright 2016 James Butler
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

BUILDPACK_INSTALL_PATH="$(cd $(dirname ${0:-}); pwd)/buildpacks"

download_buildpack() {
    buildpack_url="$1"
    buildpack_name=$(basename $buildpack_url .git)
    buildpack_commit="$2"

    # Always remove existing data as we've removed the git data
    rm -rf "${BUILDPACK_INSTALL_PATH:?}/$buildpack_name"
    echo "Fetching $buildpack_name@$buildpack_commit"

    set +e
    # Try fetching just the first few commits for efficiency
    git clone --branch $buildpack_commit --depth 10 $buildpack_url $BUILDPACK_INSTALL_PATH/$buildpack_name &>/dev/null
    SHALLOW_CLONED=$?
    set -e
    if [ $SHALLOW_CLONED -ne 0 ]; then
        # if the shallow clone failed partway through, clean up and try a full clone
        rm -rf "${BUILDPACK_INSTALL_PATH:?}/$buildpack_name"
        git clone --quiet $buildpack_url $BUILDPACK_INSTALL_PATH/$buildpack_name
        pushd $BUILDPACK_INSTALL_PATH/$buildpack_name &>/dev/null
            git checkout --quiet $buildpack_commit
            # Write out the version info as we will nuke the git info
            commit_id="$(git rev-parse HEAD)"
            echo -n "$commit_id" > version.txt
            if [ "$commit_id" !=  "$buildpack_commit" ]; then
                echo " [$buildpack_commit]" >> version.txt
            fi
            rm -rf .git
        popd &>/dev/null
    fi

    echo "Done."
}

mkdir -p "$BUILDPACK_INSTALL_PATH"

# List buildpacks here

download_buildpack https://github.com/heroku/heroku-buildpack-multi.git          v1.0.0
download_buildpack https://github.com/heroku/heroku-buildpack-ruby.git           v146
download_buildpack https://github.com/heroku/heroku-buildpack-nodejs.git         v91
download_buildpack https://github.com/heroku/heroku-buildpack-java.git           v46
download_buildpack https://github.com/heroku/heroku-buildpack-gradle.git         v18
download_buildpack https://github.com/heroku/heroku-buildpack-grails.git         v20
download_buildpack https://github.com/heroku/heroku-buildpack-play.git           v26
download_buildpack https://github.com/heroku/heroku-buildpack-python.git         v83
download_buildpack https://github.com/heroku/heroku-buildpack-php.git            v114
download_buildpack https://github.com/heroku/heroku-buildpack-clojure.git        v75
download_buildpack https://github.com/heroku/heroku-buildpack-scala.git          v72
download_buildpack https://github.com/heroku/heroku-buildpack-go.git             v52